apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '7080'
  
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 7080
      targetPort: 9090 
      nodePort: 30000